bank_marketing:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: crafty-biplane-257500
      dataset: bank_marketing
      location: US
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
      keyfile: /path/to/service-account.json  # Configurar en Cloud Shell
    
    dev:
      type: bigquery
      method: service-account
      project: crafty-biplane-257500
      dataset: bank_marketing_dev
      location: US
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
      keyfile: /path/to/service-account.json  # Configurar en Cloud Shell
    
    test:
      type: bigquery
      method: service-account
      project: crafty-biplane-257500
      dataset: bank_marketing_test
      location: US
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
      keyfile: /path/to/service-account.json  # Configurar en Cloud Shell

