version: 2

sources:
  - name: raw_data
    description: "Raw data from UCI Bank Marketing dataset"
    tables:
      - name: bank_marketing
        description: "Bank marketing campaign data"
        columns:
          - name: age
            description: "Age of the customer"
            tests:
              - not_null
              - accepted_values:
                  values: [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]
          
          - name: job
            description: "Job category"
            tests:
              - not_null
              - accepted_values:
                  values: ['admin.', 'blue-collar', 'entrepreneur', 'housemaid', 'management', 'retired', 'self-employed', 'services', 'student', 'technician', 'unemployed', 'unknown']
          
          - name: marital
            description: "Marital status"
            tests:
              - not_null
              - accepted_values:
                  values: ['divorced', 'married', 'single', 'unknown']
          
          - name: education
            description: "Education level"
            tests:
              - not_null
              - accepted_values:
                  values: ['basic.4y', 'basic.6y', 'basic.9y', 'high.school', 'illiterate', 'professional.course', 'university.degree', 'unknown']
          
          - name: default
            description: "Has credit in default"
            tests:
              - not_null
              - accepted_values:
                  values: ['no', 'unknown', 'yes']
          
          - name: housing
            description: "Has housing loan"
            tests:
              - not_null
              - accepted_values:
                  values: ['no', 'unknown', 'yes']
          
          - name: loan
            description: "Has personal loan"
            tests:
              - not_null
              - accepted_values:
                  values: ['no', 'unknown', 'yes']
          
          - name: contact
            description: "Contact communication type"
            tests:
              - not_null
              - accepted_values:
                  values: ['cellular', 'telephone']
          
          - name: month
            description: "Last contact month of year"
            tests:
              - not_null
              - accepted_values:
                  values: ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
          
          - name: day_of_week
            description: "Last contact day of the week"
            tests:
              - not_null
              - accepted_values:
                  values: ['mon', 'tue', 'wed', 'thu', 'fri']
          
          - name: duration
            description: "Last contact duration, in seconds"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  max_value: 4918
          
          - name: campaign
            description: "Number of contacts performed during this campaign"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 1
                  max_value: 56
          
          - name: pdays
            description: "Number of days that passed by after the client was last contacted"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: -1
                  max_value: 999
          
          - name: previous
            description: "Number of contacts performed before this campaign"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  max_value: 7
          
          - name: poutcome
            description: "Outcome of the previous marketing campaign"
            tests:
              - not_null
              - accepted_values:
                  values: ['failure', 'nonexistent', 'success']
          
          - name: emp_var_rate
            description: "Employment variation rate"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: -3.4
                  max_value: 1.4
          
          - name: cons_price_idx
            description: "Consumer price index"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 92.201
                  max_value: 94.767
          
          - name: cons_conf_idx
            description: "Consumer confidence index"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: -50.8
                  max_value: -26.9
          
          - name: euribor3m
            description: "Euribor 3 month rate"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0.634
                  max_value: 5.045
          
          - name: nr_employed
            description: "Number of employees"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 4963.6
                  max_value: 5228.1
          
          - name: y
            description: "Has the client subscribed a term deposit"
            tests:
              - not_null
              - accepted_values:
                  values: ['no', 'yes']
